source 'https://github.com/CocoaPods/Specs'

xcodeproj 'SRMonthPicker Tests'
workspace '../SRMonthPicker'
inhibit_all_warnings!

platform :ios, '5.0'

pod 'SRMonthPicker', :path => '..'
pod 'Kiwi', '~> 2.3'
